<?php

/**
 * @file
 * Contains webform_geonames.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_geonames_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_geonames module.
    case 'help.page.webform_geonames':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Webform address composite element using geonames API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function webform_geonames_theme() {
  return [
    'webform_geonames' => [
      'render element' => 'children',
    ],
  ];
}
